version: '3.8'

services:
  mimic3:
    image: mycroftai/mimic3
    ports:
      - "59125:59125"
    volumes:
      - "${HOME}/.local/share/mycroft/mimic3:/home/mimic3/.local/share/mycroft/mimic3"
    stdin_open: true
    tty: true

  chatgpt:
    build: .
    ports:
      - 3000:3000
    environment:
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
